FROM postgres:14

# Copy in the initial schema script
#COPY init-schema.sh /docker-entrypoint-initdb.d/init-schema.sh

# Make the script executable
#RUN chmod +x /docker-entrypoint-initdb.d/init-schema.sh