"""Changing to role scope instead of rolescopetenant

Revision ID: 24389cea08c4
Revises: 
Create Date: 2021-10-07 18:57:09.975840

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '24389cea08c4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('RoleScope',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('scope_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['web.Role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['scope_id'], ['web.Scope.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'scope_id'),
    schema='web'
    )
    op.create_index(op.f('ix_web_Feature_layer_id'), 'Feature', ['layer_id'], unique=False, schema='web')
    op.drop_index('layer_index', table_name='Feature', schema='web')
    op.create_index(op.f('ix_web_Field_field_config_id'), 'Field', ['field_config_id'], unique=False, schema='web')
    op.create_foreign_key(None, 'Layer', 'Section', ['id_section'], ['id'], source_schema='web', referent_schema='web')
    op.add_column('Role', sa.Column('tenant_id', sa.Integer()), schema='web')
    op.create_foreign_key(None, 'Role', 'Tenant', ['tenant_id'], ['id'], source_schema='web', referent_schema='web')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Role', schema='web', type_='foreignkey')
    op.drop_column('Role', 'tenant_id', schema='web')
    op.drop_constraint(None, 'Layer', schema='web', type_='foreignkey')
    op.drop_index(op.f('ix_web_Field_field_config_id'), table_name='Field', schema='web')
    op.create_index('layer_index', 'Feature', ['layer_id'], unique=False, schema='web')
    op.drop_index(op.f('ix_web_Feature_layer_id'), table_name='Feature', schema='web')
    op.drop_table('RoleScope', schema='web')
    # ### end Alembic commands ###
