"""Initial migration.

Revision ID: 064054375ecb
Revises: 
Create Date: 2023-03-28 11:29:53.130758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import orm

# revision identifiers, used by Alembic.
revision = '064054375ecb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE SCHEMA IF NOT EXISTS web;')
    op.execute('CREATE SCHEMA IF NOT EXISTS datalake;')
    op.create_table('events',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.String(length=55), nullable=True),
                    sa.Column('lat', sa.String(length=55), nullable=True),
                    sa.Column('lng', sa.String(length=55), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='datalake'
                    )
    op.create_table('Dashboard',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=55), nullable=True),
                    sa.Column('dt_created', sa.DATE(), nullable=True),
                    sa.Column('origin', sa.String(length=55), nullable=True),
                    sa.Column('layout_grid', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('Scope',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('description', sa.String(
                        length=500), nullable=True),
                    sa.Column('key', sa.String(length=500), nullable=True),
                    sa.Column('name', sa.String(length=500), nullable=True),
                    sa.Column('last_update', sa.DateTime(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('Tenant',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('city', sa.String(length=255), nullable=True),
                    sa.Column('city_code', sa.String(
                        length=255), nullable=True),
                    sa.Column('country', sa.String(length=255), nullable=True),
                    sa.Column('status', sa.SMALLINT(), nullable=True),
                    sa.Column('last_update', sa.DateTime(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('User',
                    sa.Column('id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('uid', sa.String(length=200), nullable=True),
                    sa.Column('name', sa.String(length=500), nullable=True),
                    sa.Column('email', sa.String(length=200), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('last_update', sa.DateTime(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email'),
                    schema='web'
                    )
    op.create_table('field',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('key', sa.String(length=55), nullable=True),
                    sa.Column('value', sa.String(length=55), nullable=True),
                    sa.Column('type', sa.String(length=55), nullable=True),
                    sa.Column('origin', sa.String(length=55), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('filter',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_layer', sa.Integer(), nullable=False),
                    sa.Column('id_group', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('generic_queries',
                    sa.Column('query_key', sa.TEXT(), nullable=False),
                    sa.Column('tenant', sa.TEXT(), nullable=False),
                    sa.Column('type', sa.TEXT(), nullable=True),
                    sa.Column('query_sql', sa.TEXT(), nullable=True),
                    sa.Column('filters', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.Column('layers', postgresql.JSONB(
                        astext_type=sa.Text()), nullable=True),
                    sa.PrimaryKeyConstraint('query_key', 'tenant'),
                    schema='web'
                    )
    op.create_table('group',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.String(length=55), nullable=False),
                    sa.Column('origin', sa.String(length=3), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('issue',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('date', sa.DateTime(), nullable=False),
                    sa.Column('user', sa.String(length=100), nullable=False),
                    sa.Column('title', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('version', sa.String(
                        length=100), nullable=False),
                    sa.Column('image', sa.Text(), nullable=True),
                    sa.Column('origin', sa.String(length=3), nullable=True),
                    sa.Column('status', sa.String(length=55), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('prediction_precision',
                    sa.Column('n_sectors', sa.String(
                        length=55), nullable=True),
                    sa.Column('algorithm', sa.String(
                        length=55), nullable=True),
                    sa.Column('model_date', sa.String(
                        length=55), nullable=True),
                    sa.Column('run_time', sa.String(length=55), nullable=True),
                    sa.Column('f1', sa.String(length=55), nullable=True),
                    sa.Column('f1_threshold', sa.String(
                        length=55), nullable=True),
                    sa.Column('f2', sa.String(length=55), nullable=True),
                    sa.Column('f2_threshold', sa.String(
                        length=55), nullable=True),
                    sa.Column('training_start', sa.String(
                        length=55), nullable=True),
                    sa.Column('training_end', sa.String(
                        length=55), nullable=True),
                    sa.Column('prediction_for', sa.String(
                        length=55), nullable=True),
                    sa.Column('model_path', sa.String(
                        length=55), nullable=True),
                    sa.Column('observation', sa.String(
                        length=55), nullable=True),
                    sa.Column('layer', sa.String(length=55), nullable=False),
                    sa.Column('prediction_date', sa.String(
                        length=55), nullable=False),
                    sa.PrimaryKeyConstraint('layer', 'prediction_date'),
                    schema='web'
                    )
    op.create_table('profile',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('uid', sa.String(length=55), nullable=False),
                    sa.Column('name', sa.String(length=55), nullable=True),
                    sa.Column('email', sa.String(length=55), nullable=False),
                    sa.Column('role', sa.String(length=55), nullable=False),
                    sa.Column('active', sa.Boolean(), nullable=False),
                    sa.Column('origin', sa.String(length=55), nullable=True),
                    sa.PrimaryKeyConstraint('id', 'uid'),
                    schema='web'
                    )
    op.create_table('section',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=55), nullable=True),
                    sa.Column('icon', sa.String(length=55), nullable=True),
                    sa.Column('position', sa.Integer(), nullable=True),
                    sa.Column('origin', sa.String(length=55), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('section_layer',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_section', sa.Integer(), nullable=True),
                    sa.Column('id_layer', sa.Integer(), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('unavailable_dates',
                    sa.Column('origin', sa.String(length=55), nullable=True),
                    sa.Column('id_layer', sa.BIGINT(), nullable=False),
                    sa.Column('dt_filter', sa.String(
                        length=55), nullable=True),
                    sa.PrimaryKeyConstraint('id_layer'),
                    schema='web'
                    )
    op.create_table('AuditLog',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=True),
                    sa.Column('user_name', sa.String(
                        length=100), nullable=True),
                    sa.Column('action', sa.String(length=255), nullable=True),
                    sa.Column('url', sa.String(length=255), nullable=True),
                    sa.Column('ip', sa.String(length=55), nullable=True),
                    sa.Column('browser', sa.String(length=255), nullable=True),
                    sa.Column('object_type', sa.String(
                        length=255), nullable=True),
                    sa.Column('object_name', sa.String(
                        length=255), nullable=True),
                    sa.Column('object_id', sa.Integer(), nullable=True),
                    sa.Column('data', sa.JSON(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('tenant', sa.String(length=55), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['user_id'], ['web.User.id'], ondelete='RESTRICT'),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('ChartType',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('tenant_id', sa.Integer(), nullable=False),
                    sa.Column('key', sa.String(length=255), nullable=True),
                    sa.Column('extra_props', sa.TEXT(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('last_update', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['web.Tenant.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('DashboardItem',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('id_dashboard', sa.Integer(), nullable=True),
                    sa.Column('tipo', sa.String(length=55), nullable=True),
                    sa.Column('titulo', sa.String(length=55), nullable=True),
                    sa.Column('sql', sa.String(length=255), nullable=True),
                    sa.Column('filters', sa.JSON(), nullable=True),
                    sa.Column('grid_line', sa.String(
                        length=255), nullable=True),
                    sa.Column('grid_col', sa.String(
                        length=255), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['id_dashboard'], ['web.Dashboard.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('FeatureCollection',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('bbox', sa.String(length=255), nullable=True),
                    sa.Column('bucket_url', sa.String(
                        length=255), nullable=True),
                    sa.Column('tenant_id', sa.Integer(), nullable=False),
                    sa.Column('view', sa.String(length=255), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('last_update', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['web.Tenant.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('FieldConfig',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('tenant_id', sa.Integer(), nullable=True),
                    sa.Column('key', sa.String(length=255), nullable=True),
                    sa.Column('label', sa.JSON(), nullable=True),
                    sa.Column('visible', sa.Boolean(), nullable=True),
                    sa.Column('order', sa.Integer(), nullable=True),
                    sa.Column('type', sa.String(length=255), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['web.Tenant.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('Role',
                    sa.Column('id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('name', sa.String(), nullable=True),
                    sa.Column('default', sa.Boolean(), nullable=True),
                    sa.Column('last_update', sa.DateTime(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('tenant_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['web.Tenant.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('Section',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('tenant', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('icon', sa.String(length=255), nullable=True),
                    sa.Column('order', sa.Integer(), nullable=True),
                    sa.Column('label', sa.JSON(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('last_update', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['tenant'], ['web.Tenant.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('Tab',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('tenant_id', sa.Integer(), nullable=False),
                    sa.Column('key', sa.String(length=255), nullable=True),
                    sa.Column('label', sa.JSON(), nullable=True),
                    sa.Column('priority', sa.Integer(), nullable=True),
                    sa.Column('visible', sa.Boolean(), nullable=True),
                    sa.Column('selected', sa.Boolean(), nullable=True),
                    sa.Column('style', sa.TEXT(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('last_update', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['web.Tenant.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('Chart',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('tenant_id', sa.Integer(), nullable=False),
                    sa.Column('charttype_id', sa.Integer(), nullable=False),
                    sa.Column('label', sa.JSON(), nullable=True),
                    sa.Column('key', sa.String(length=255), nullable=True),
                    sa.Column('query_sql', sa.TEXT(), nullable=True),
                    sa.Column('visible', sa.Boolean(), nullable=True),
                    sa.Column('style', sa.TEXT(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('last_update', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['charttype_id'], ['web.ChartType.id'], ),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['web.Tenant.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('FieldConfigOptions',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('field_config_id', sa.Integer(), nullable=True),
                    sa.Column('tenant_id', sa.Integer(), nullable=True),
                    sa.Column('key', sa.String(length=255), nullable=True),
                    sa.Column('label', sa.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(['field_config_id'], [
                                            'web.FieldConfig.id'], ),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['web.Tenant.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('Layer',
                    sa.Column('id', sa.Integer(),
                              autoincrement=False, nullable=False),
                    sa.Column('tenant', sa.Integer(), nullable=False),
                    sa.Column('id_section', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=255), nullable=True),
                    sa.Column('selected', sa.Boolean(), nullable=True),
                    sa.Column('order', sa.Integer(), nullable=True),
                    sa.Column('active', sa.Boolean(), nullable=True),
                    sa.Column('style', sa.JSON(), nullable=True),
                    sa.Column('editable', sa.Boolean(), nullable=True),
                    sa.Column('label', sa.JSON(), nullable=True),
                    sa.Column('configurable', sa.Boolean(), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('last_update', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['id_section'], ['web.Section.id'], ),
                    sa.ForeignKeyConstraint(['tenant'], ['web.Tenant.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('RoleScope',
                    sa.Column('role_id', sa.Integer(), nullable=False),
                    sa.Column('scope_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['role_id'], ['web.Role.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['scope_id'], ['web.Scope.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('role_id', 'scope_id'),
                    schema='web'
                    )
    op.create_table('UserRoleTenant',
                    sa.Column('UserID', sa.Integer(), nullable=False),
                    sa.Column('RoleID', sa.Integer(), nullable=False),
                    sa.Column('TenantID', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['RoleID'], ['web.Role.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['TenantID'], ['web.Tenant.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['UserID'], ['web.User.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('UserID', 'RoleID', 'TenantID'),
                    schema='web'
                    )
    op.create_table('ChartTypeTabLayer',
                    sa.Column('charttype_id', sa.Integer(), nullable=False),
                    sa.Column('tab_id', sa.Integer(), nullable=False),
                    sa.Column('layer_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['charttype_id'], ['web.ChartType.id'], ),
                    sa.ForeignKeyConstraint(['layer_id'], ['web.Layer.id'], ),
                    sa.ForeignKeyConstraint(['tab_id'], ['web.Tab.id'], ),
                    sa.PrimaryKeyConstraint(
                        'charttype_id', 'tab_id', 'layer_id'),
                    schema='web'
                    )
    op.create_table('Feature',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('code', sa.String(length=255), nullable=True),
                    sa.Column('tenant_id', sa.Integer(), nullable=False),
                    sa.Column('layer_id', sa.Integer(), nullable=False),
                    sa.Column('feature_collection_id',
                              sa.Integer(), nullable=False),
                    sa.Column('geometry', sa.String(
                        length=1000), nullable=False),
                    sa.Column('type', sa.String(length=255), nullable=True),
                    sa.Column('view', sa.String(length=255), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('last_update', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(['feature_collection_id'], [
                        'web.FeatureCollection.id'], ),
                    sa.ForeignKeyConstraint(['layer_id'], ['web.Layer.id'], ),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['web.Tenant.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_index(op.f('ix_web_Feature_layer_id'), 'Feature',
                    ['layer_id'], unique=False, schema='web')
    op.create_table('FieldConfigLayer',
                    sa.Column('layer_id', sa.Integer(), nullable=False),
                    sa.Column('fieldconfig_id', sa.Integer(), nullable=False),
                    sa.Column('tenant_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['fieldconfig_id'], [
                                            'web.FieldConfig.id'], ),
                    sa.ForeignKeyConstraint(['layer_id'], ['web.Layer.id'], ),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['web.Tenant.id'], ),
                    sa.PrimaryKeyConstraint(
                        'layer_id', 'fieldconfig_id', 'tenant_id'),
                    schema='web'
                    )
    op.create_table('Calendar',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('tenant_id', sa.Integer(), nullable=False),
                    sa.Column('layer_id', sa.Integer(), nullable=False),
                    sa.Column('feature_id', sa.Integer(), nullable=False),
                    sa.Column('available_date', sa.Date(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['feature_id'], ['web.Feature.id'], ),
                    sa.ForeignKeyConstraint(['layer_id'], ['web.Layer.id'], ),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['web.Tenant.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_table('Field',
                    sa.Column('id', sa.Integer(),
                              autoincrement=True, nullable=False),
                    sa.Column('field_config_id', sa.Integer(), nullable=True),
                    sa.Column('feature_id', sa.Integer(), nullable=True),
                    sa.Column('date', sa.Date(), nullable=True),
                    sa.Column('tenant_id', sa.Integer(), nullable=True),
                    sa.Column('key', sa.String(length=255), nullable=True),
                    sa.Column('value', sa.String(length=255), nullable=True),
                    sa.Column('extra_props', sa.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['feature_id'], ['web.Feature.id'], ),
                    sa.ForeignKeyConstraint(['field_config_id'], [
                                            'web.FieldConfig.id'], ),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['web.Tenant.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_index(op.f('ix_web_Field_date'), 'Field', [
                    'date'], unique=False, schema='web')
    op.create_index(op.f('ix_web_Field_feature_id'), 'Field', [
                    'feature_id'], unique=False, schema='web')
    op.create_index(op.f('ix_web_Field_field_config_id'), 'Field', [
                    'field_config_id'], unique=False, schema='web')
    op.create_index(op.f('ix_web_Field_tenant_id'), 'Field', [
                    'tenant_id'], unique=False, schema='web')
    op.create_table('Properties',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('feature_id', sa.Integer(), nullable=False),
                    sa.Column('tenant_id', sa.Integer(), nullable=False),
                    sa.Column('image', sa.String(length=255), nullable=True),
                    sa.Column('style', sa.String(length=255), nullable=True),
                    sa.Column('display_name', sa.String(
                        length=255), nullable=True),
                    sa.Column('label', sa.String(length=255), nullable=True),
                    sa.Column('creation_date', sa.DateTime(), nullable=True),
                    sa.Column('last_update', sa.DateTime(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['feature_id'], ['web.Feature.id'], ),
                    sa.ForeignKeyConstraint(
                        ['tenant_id'], ['web.Tenant.id'], ),
                    sa.PrimaryKeyConstraint('id'),
                    schema='web'
                    )
    op.create_index(op.f('ix_web_Properties_feature_id'), 'Properties', [
                    'feature_id'], unique=False, schema='web')
    # create User for each User name
    op.execute("INSERT INTO web.\"Tenant\" (id, name, city, city_code, country, status, last_update, creation_date) VALUES (1, 'Criciuma', 'Criciuma', 'SC', 'Santa Catarina', 1, '2021-02-08 16:21:06.000000', '2021-02-08 16:21:09.000000')")
    op.execute(
        "INSERT INTO web.\"Section\" (id, tenant, name, icon, \"order\", label, creation_date, last_update) VALUES (1, 1, ''Past Incidents'', ''mdi-layers'', 1, ''{ \"en\":\"Past Incidents\", \"pt\":\"Ocorrências\" }'', ''2021 - 10 - 22 00:21:56.000000'', ''2021 - 10 - 22 00:21:56.000000'')")

    op.execute("INSERT INTO web.\"User\" (uid, name, email, active) SELECT 'vCeFFximIXayqXsMuV6aFsT01c02', 'gabriel', 'gabriel@igarape.org.br', true")
    op.execute("INSERT INTO web.\"Layer\" (id, tenant, id_section, name, selected, \"order\", active, style, editable, label, configurable, creation_date, last_update) VALUES (1, 1, 1, 'Ocorrências', false, 2, true, '{\"colorScale\": { \"point\": {} , \"polygon\": [\"hsl(230, 100%, 50%)\", \"hsl(180, 100%, 50%)\", \"hsl(120, 100%, 50%)\", \"hsl(60, 100%, 50%)\", \"hsl(0, 100%, 50%)\"], \"image_overlay\": [] }, \"color\": \"#FFFFFF\", \"types\": [{\"name\": \"scale\", \"value\": true, \"icon\": \"mdi-palette\", \"label\": \"scale\"}, {\"name\": \"hexagon\", \"value\": false, \"icon\": \"mdi-format-paint\", \"label\": \"hexagon\"}, {\"name\": \"icon\", \"value\": false, \"icon\": \"mdi-star-circle\", \"label\": \"icon\"}, {\"name\": \"marker\", \"value\": false, \"icon\": \"mdi-map-marker\", \"label\": \"marker\"}, {\"name\": \"point\", \"value\": false, \"icon\": \"mdi-brightness-1\", \"label\": \"point\"}], \"texture\": {\"value\": \"NONE\", \"options\": [\"NONE\", \"HORIZONTAL\", \"VERTICAL\"]}, \"extra_props\": { \"marker\": { \"image\": \"\", \"icon\": \"pin-black.png\"}, \"image_overlay\": {}, \"polygon\": {}, \"point\": {}, \"mobile\": true, \"type\": \"!icon\" }}', false, '{\"en\": \"Emergency Calls\", \"pt\": \"Ocorr\u00eancias\"}', true, '2021-09-20 11:06:31.000000', '2021-10-04 22:24:01.715321')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (1, 'View navbar Map Page Option', 'map.view', 'Map Option View', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (2, 'View optimization Option', 'optimization.view', 'Optimization Option View', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (4, 'View helper Option', 'helper.view', 'Helper Option View', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (5, 'Select layers in sidebar menu', 'map.layer.view', 'Layers View', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (6, 'Select reset button option', 'map.reset.view', 'View Reset Button', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (7, 'Select apply button option', 'map.apply.view', 'View Apply Button', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (8, 'Select filter options', 'map.filter.view', 'View and Select Filters', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (9, 'Select dates options', 'map.date.view', 'View and Select calendar dates', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (10, 'Select texture options', 'map.texture.view', 'View and Select different textures', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (11, 'Select map types', 'map.type.view', 'View box and Select Map types', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000');")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (12, 'View Map Captions', 'map.caption.view', 'View Map Captions floating options', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000');")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (13, 'View Toolbox', 'map.toolbox.view', 'View and use Toolbox', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (14, 'View SearchBar', 'map.search.view', 'View and use Searchbar', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (15, 'View Controls Pane', 'map.control.view', 'View and use Controls Pane', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (16, 'List Users', 'user.list.view', 'List Users and use Filters', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (17, 'Create Users', 'user.create', 'Create users in Tenant', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (18, 'Delete Users', 'user.delete', 'Delete a user from a Tenant', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (19, 'Associate Profiles to Users', 'user.edit', 'Edit a user in Tenant', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (20, 'View Reports', 'report.search.view', 'View Reports', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (21, 'Edit Status Reports', 'report.status.edit', 'Edit Status Reports', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (22, 'View Predictions', 'prediction.list.view', 'View Predictions Reports', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (23, 'Search Predictions', 'prediction.search.view', 'Search Predictions Reports', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (24, 'Associate Roles to Users and Scopes', 'role.edit', 'Edit a role in Tenant', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (25, 'Create Roles', 'role.create', 'Create a role in Tenant', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (26, 'Delete Roles', 'role.delete', 'Delete a role in Tenant', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (27, 'List Roles', 'role.list.view', 'List roles in Tenant', '2021-09-28 15:01:06.000000', '2021-09-28 15:01:08.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (28, 'Scope List', 'scope.list.view', 'List scopes in Tenant', '2021-09-28 15:02:43.000000', '2021-09-28 15:02:46.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (29, 'Management View ', 'management.view', 'Management View', '2021-09-28 15:01:06.000000', '2021-09-28 15:01:08.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (30, 'Feedback View', 'feedback.view', 'Feedback View', '2021-09-28 15:02:43.000000', '2021-09-28 15:02:46.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (31, 'Administration View', 'administration.view', 'Administration View', '2021-09-28 15:02:43.000000', '2021-09-28 15:02:46.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (32, 'Section Create', 'section.create', 'Create Sections in Tenant', '2021-09-28 15:02:43.000000', '2021-09-28 15:02:46.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (33, 'Section List View', 'section.list.view', 'List Sections in Tenant', '2021-09-28 15:02:43.000000', '2021-09-28 15:02:46.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (34, 'Section Edit', 'section.edit', 'Edit Sections in Tenant', '2021-09-28 15:02:43.000000', '2021-09-28 15:02:46.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (35, 'Section Delete', 'section.delete', 'Delete Sections in Tenant', '2021-09-28 15:02:43.000000', '2021-09-28 15:02:46.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (36, 'Layer Create', 'layer.create', 'Create new Layers in Tenant', '2021-09-28 15:02:43.000000', '2021-09-28 15:02:46.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (37, 'Layer List View', 'layer.list.view', 'List Layers in Tenant', '2021-09-28 15:02:43.000000', '2021-09-28 15:02:43.000000')")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (38, 'Layer Edit', 'layer.edit', 'Edit Layers in Tenant', '2021-09-28 15:02:43.000000', '2021-09-28 15:02:43.000000');")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (39, 'Layer Delete', 'layer.delete', 'Delete Layers in Tenant', '2021-09-28 15:02:43.000000', '2021-09-28 15:02:43.000000');")
    op.execute("INSERT INTO web.\"Scope\" (id, description, key, name, last_update, creation_date) VALUES (3, 'View user feedback Option', 'feedback.view', 'User Feedback Option View', '2021-02-08 16:31:39.000000', '2021-02-08 16:31:42.000000');")

    session.commit()
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_web_Properties_feature_id'),
                  table_name='Properties', schema='web')
    op.drop_table('Properties', schema='web')
    op.drop_index(op.f('ix_web_Field_tenant_id'),
                  table_name='Field', schema='web')
    op.drop_index(op.f('ix_web_Field_field_config_id'),
                  table_name='Field', schema='web')
    op.drop_index(op.f('ix_web_Field_feature_id'),
                  table_name='Field', schema='web')
    op.drop_index(op.f('ix_web_Field_date'), table_name='Field', schema='web')
    op.drop_table('Field', schema='web')
    op.drop_table('Calendar', schema='web')
    op.drop_table('FieldConfigLayer', schema='web')
    op.drop_index(op.f('ix_web_Feature_layer_id'),
                  table_name='Feature', schema='web')
    op.drop_table('Feature', schema='web')
    op.drop_table('ChartTypeTabLayer', schema='web')
    op.drop_table('UserRoleTenant', schema='web')
    op.drop_table('RoleScope', schema='web')
    op.drop_table('Layer', schema='web')
    op.drop_table('FieldConfigOptions', schema='web')
    op.drop_table('Chart', schema='web')
    op.drop_table('Tab', schema='web')
    op.drop_table('Section', schema='web')
    op.drop_table('Role', schema='web')
    op.drop_table('FieldConfig', schema='web')
    op.drop_table('FeatureCollection', schema='web')
    op.drop_table('DashboardItem', schema='web')
    op.drop_table('ChartType', schema='web')
    op.drop_table('AuditLog', schema='web')
    op.drop_table('unavailable_dates', schema='web')
    op.drop_table('section_layer', schema='web')
    op.drop_table('section', schema='web')
    op.drop_table('profile', schema='web')
    op.drop_table('prediction_precision', schema='web')
    op.drop_table('issue', schema='web')
    op.drop_table('group', schema='web')
    op.drop_table('generic_queries', schema='web')
    op.drop_table('filter', schema='web')
    op.drop_table('field', schema='web')
    op.drop_table('User', schema='web')
    op.drop_table('Tenant', schema='web')
    op.drop_table('Scope', schema='web')
    op.drop_table('Dashboard', schema='web')
    # ### end Alembic commands ###
